name: Check Repo Size

on:
  workflow_dispatch:

jobs:
  repo-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Repository Size
        run: |
          # Fetch repo size from GitHub API
          REPO_SIZE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }} | jq '.size')
          
          echo "Repository size: ${REPO_SIZE} KB"
